### PR TITLE
Add default syslog-ng config

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
@william-gr it is responsible for writing text logs (journald only writes it's own binary format) and also sending to remote syslog.

**Comment by sonicaj** [comment]
@themylogin shouldn't we be doing this in a single place ? We are already copying files for mail in truenas post install. If you think this is a better place, we can do that here ?

**Comment by themylogin** [comment]
I agree with you, thank you for noticing this

**Comment by themylogin** [comment]
Are we sure `truenas` script is the last thing that gets executed in the package installation stage? (I need this for groups and passwd)

**Comment by sonicaj** [comment]
@themylogin we should make sure if it isn't. To my understanding, it acts a meta port finalising the dependencies, so it's post install should be good for this.

**Pull request merged**
