### PR TITLE
NAS-109351 / 21.04 / Generate native systemd unit files for SysV services that lack ones t…

### PR DESCRIPTION
**Pull request by themylogin**
…o prevent systemd-sysv-generator warnings

### CODE REVIEW

**Review by yocalebo — COMMENTED** [review]
Are you worried that the generated service files for a more complex service like `SCST`, for example, will not be correct? Thinking of the `RemainAfterExit` parameter and such.

**Comment by themylogin** [comment]
@sonicaj it is known why scst does not have a native systemd unit file?

**Comment by yocalebo** [comment]
> @sonicaj it is known why scst does not have a native systemd unit file?

I've looked into this and found https://github.com/bvanassche/scst/issues/29, as it's already been asked. I believe it's just a matter of not creating one upstream...

**Comment by sonicaj** [comment]
@yocalebo yes, that's accurate. However i am not sure how this change changes anything wrt scst ?

**Comment by yocalebo** [comment]
> @yocalebo yes, that's accurate. However i am not sure how this change changes anything wrt scst ?

Because automatically generating systemd unit files isn't perfect. `SCST` is a complex service so I'm wondering if the automatically generated one will be the "correct" one.

**Comment by sonicaj** [comment]
Well it's already happening ? The concerns are valid but the scope of this change seems different ?

**Comment by sonicaj** [comment]
I think we can perhaps create a new ticket to ensure that the services we officially support don't have an issue in their generated systemd files ( if they are generated ) and if they do, we can either create issues upstream and if possible maybe even contribute upstream. Thoughts ?

**Comment by yocalebo** [comment]
> I think we can perhaps create a new ticket to ensure that the services we officially support don't have an issue in their generated systemd files ( if they are generated ) and if they do, we can either create issues upstream and if possible maybe even contribute upstream. Thoughts ?

If you think the generated service file works, then I'm fine and I agree, I only bring up `SCST` since I consider it a "core" service. Seems strange to not have a native systemd service file.

**Comment by sonicaj** [comment]
@yocalebo to the best of my knowledge we have not had issues so far. I think we are good, and if we see issues we can of course fix those.

**Review by sonicaj — APPROVED** [review]

**Pull request merged**
