### PR TITLE
WIP OpenZFS 2.0 update

### PR DESCRIPTION
**Pull request by freqlabs**

### CODE REVIEW

**Comment by kmoore134** [comment]
retest this please

**Review by william-gr — APPROVED** [review]
LGTM, I supposed we will merge each of the repos from openzfs to master branch and not change it here?

**Review by kmoore134 — APPROVED** [review]
Approved as well. Agree with William, lets merge all the 'openzfs' branches into 'master' in their respective repos, and then reset pointing to master here before merge.

**Comment by freqlabs** [comment]
Final version in #51

**Pull request closed without merging**
